# Generated by Django 4.1 on 2022-08-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mchongoTZ', '0002_alter_cart_price_alter_invoice_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
